# Node.js with React
# Build a Node.js project that uses React for MediSync.

trigger:
  branches:
    include:
    - Ml

stages:
- stage: BuildStage
  displayName: 'Build MediSync Frontend'
  jobs:
  - job: BuildJob
    pool:
      vmImage: ubuntu-latest
    steps:
    # 1. Setup Node.js environment
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    # 2. Install dependencies and compile the React app
    - task: CmdLine@2
      displayName: 'npm install and build'
      inputs:
        script: |
          npm install
          CI=false npm run build
        workingDirectory: 'Frontend'

    # 3. Save the build folder (Updated to 'dist')
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'
      inputs:
        PathtoPublish: 'Frontend/dist' 
        ArtifactName: 'MediSync-Build'
        publishLocation: 'Container'